---
- name: Install yum-cron.
  package: name=yum-cron state=present

- name: Ensure yum-cron is running and enabled on boot.
  service: name=yum-cron state=started enabled=yes

- name: Configure autoupdates (RHEL 7) and copy yum-cron configuration files in place.
  template:
    src: "../templates/{{ item }}.j2"
    dest: "/etc/yum/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - yum-cron.conf
  when: security_autoupdate_enabled
